//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MotoSoft.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "16.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vladisla-MotoSoft-PRD-6ea920fd0-baef81df")]
        public string APP_ID {
            get {
                return ((string)(this["APP_ID"]));
            }
            set {
                this["APP_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4a0a3d23-faba-49cb-8651-d32492ca4ca3")]
        public string DEV_ID {
            get {
                return ((string)(this["DEV_ID"]));
            }
            set {
                this["DEV_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("PRD-ea920fd07250-4174-4006-9425-6fe7")]
        public string CER_ID {
            get {
                return ((string)(this["CER_ID"]));
            }
            set {
                this["CER_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AgAAAA**AQAAAA**aAAAAA**j9LJXA**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6ACloWoDZOBoAidj6x9nY+seQ**M/wFAA**AAMAAA**JbTjG4xi7lm/2e4PB71br/H8bZ4Fkh4t505kiD2CIPvTrHCNkq8FqgcHrUrm6RIi1fbcAwQS6pdKAt7hZpl2fFmt7MAIjzs0Z5FJVh5OaCG0sWRmfQ4zVGPIlxdkYT/urBq4lBafmT7MsxZG/vnSUv44crcVqJdczVXtk7qCzCGv6xgd2h+yHGYFQwub2h/ZpxqsIpyl6fG+TbuDEg9WabJME4vYgEUGyrgXVNrDYMvXjJ8BCL/sEkIvrhxoi9SsuP3Obf/ZFlpLBuGsANJfka3XMntw67IfMOD84fwLpaKn9YRA+4ZYQm0qw4TlTckjXCmxQ/jaxMduCJysmtGXLMKpWxgHKRcwLlQ9RBOjrMzXuK/xMwUDSbjFD6DqqDpTo/FvpYBD7lojtOfcDG23Pv4JKRl/4FJdSZ7alZgLXxqEfXlSXPywDE257cRMTlr3xj1MDILyb0AVXr1usR2KZrBhA79EBcBcH4SA/PDoFAxyuad3ni1/ABk+MGQc9UgkRA/WVQwHE73Sx7idr334LMTEfj1yWY+SS7E1fAPqgoxoXN9hToa7Oc2zGPt67D7e6NJ8awf9ObRlItMz8CfIqqwym4x9B1gD/9s8HH6Q/Ag7zuYNS0tR1QO0k6pAPpjddxN4fp9/T47Cnrq+HUxuRukmS3q7rA+9t0ki5i4StLuH3O5iFtFeGyoPE+qhFA3can6yiSIqysMqpsFsGpcBGS61eJqutRw1FFfaCH7Ez4zLXul2At7GYCLfH6bCLOtc")]
        public string eBayToken {
            get {
                return ((string)(this["eBayToken"]));
            }
            set {
                this["eBayToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vladislav_Gnato-Vladisla-MotoSo-ypsfzj")]
        public string redirecturi {
            get {
                return ((string)(this["redirecturi"]));
            }
            set {
                this["redirecturi"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vladisla-MotoSoft-SBX-beaa02434-56302677")]
        public string SAPP_ID {
            get {
                return ((string)(this["SAPP_ID"]));
            }
            set {
                this["SAPP_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("4a0a3d23-faba-49cb-8651-d32492ca4ca3")]
        public string SDEV_ID {
            get {
                return ((string)(this["SDEV_ID"]));
            }
            set {
                this["SDEV_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("SBX-eaa024340ab1-50a9-4e1e-9adf-dd69")]
        public string SCER_ID {
            get {
                return ((string)(this["SCER_ID"]));
            }
            set {
                this["SCER_ID"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute(@"AgAAAA**AQAAAA**aAAAAA**eybMXA**nY+sHZ2PrBmdj6wVnY+sEZ2PrA2dj6wFk4aiCZKCqQmdj6x9nY+seQ**FvwEAA**AAMAAA**ngTjt9WsvfwlYsKj/j5VdHs0C61gHRVkQnfCoha+AThGzRdh9dV8cAP+s1y0UekrYV+Y3n7KRvIJdEGXI5x5ok7yOTxjTD9M6Ch2tYOs/IY4dKGaoK+x6wgWi83BwQe7kQNvA2bxSgb17qILmR1S+ScL0Lzq9Pdj9UiKZN4H4UuprrrWr7Wn9KKEPv2Vf6iWfwZrWXIY0kfCVkVMEwgZDKodNtDtfcAzDY3rET8LFkuFpCet+sqIiLkEhodVW8vE7u2Yj7Nwc8WLvWgdAi0NTtu3ADi6eytMomMTjkeUKxbNyI5ROsTcPy1JCCivUHxS1EbCOjoOG3dz++37Xxog7vX5KfXIGR72AR3r+Q0onbxXvrh8VYpxMvK4sFyieiDGohdTnkatIYtxcT8O+mEsMh0Ch784Z1ba7yLAU+ybWV/EVsQd8T34VzzPZv3PuukWaebs+TW6tNbNlwMF8/sWjwue/ENHy99dqusGDXSveGXBVIB6G9gVl3lCv64+ywRwzg9hoPR6gi2+EQ5bR4TlWizljQP8/YP4GWdTcA77BfcqLuofJp3ZHt1TvDNXtcMqiXbSiq51ZVS1PUZu7VXM3MY0aiX297/rnl8n1MyO0k5qbgYEWUCn7JaPeFFK+JucaRv1e5lczTz5mbuGW2mIZ3Nm4I1a2jXTzsCgmQGQzMYWq+uG0c62/PViUPa1wt54jEc+9pkcFx48ALRzUVor4JxJtD54CWvecbrziSL+HoVBB9Y3YQcncGUUmLrxx427")]
        public string SeBayToken {
            get {
                return ((string)(this["SeBayToken"]));
            }
            set {
                this["SeBayToken"] = value;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("Vladislav_Gnato-Vladisla-MotoSo-ijvkgi")]
        public string Sredirecturi {
            get {
                return ((string)(this["Sredirecturi"]));
            }
            set {
                this["Sredirecturi"] = value;
            }
        }
    }
}
